<a href="https://colab.research.google.com/github/ucfilho/raianars_fly/blob/master/PSO_jul_08_2018.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import pandas as pd

In [0]:
'''Rosembrock Function'''
def Rosenbrock(x):
    fun=0
    a=1.0
    b=100.0
    fun = (a-x[0])**2 + b*(x[1]-x[0]**2)**2
    return fun

In [0]:
''' 
FOBJ gera vetorialmente os valores com a funcao objetivo escalar
em outras palavras gera para populacao o valor da funcao 
a ser otimizada
'''
def FOBJ(X):
    rows = X.shape[0]
    fobj=np.zeros(rows)
    for i in range(rows):
        fobj[i]=Rosenbrock(X[i,])
    return fobj

In [0]:
'''Enxame retorna a populacao aleatoria'''  
def Enxame(PAR,NPAR,MAX,MIN):
    x=np.zeros((NPAR, len(MAX)))
    for j in range(len(MAX)):
        for i in range(NPAR):
            x[i,j]=MIN[j]+(MAX[j]-MIN[j])*np.random.random()
    return x

In [0]:
'''
VE rotina velocidade utilizada na correcao das particulas
'''
def VE(X,VEL,BEST,PBEST,W,C1,C2,MAX,MIN):
    rows = X.shape[0]
    cols = X.shape[1]
    VEL=np.zeros((rows, cols))
    for i in range(rows):
        for j in range(cols):
            R1=np.random.random()
            R2=np.random.random()
            VELOCIDADE=W*VEL[i,j]+C1*R1*(PBEST[i,j]-X[i,j])+C2*R2*(BEST[j]-X[i,j])
            if(VELOCIDADE> MAX[j]):
                VELOCIDADE=0.2*MAX[j]
            if(VELOCIDADE<MIN[j]):
                VELOCIDADE=0.2*MIN[j]
            VEL[i,j]=np.copy(VELOCIDADE)
            X[i,j]=X[i,j]+VEL[i,j]
    return X, VEL

In [0]:
'''PART atualiza PBEST (melhor de cada particula)'''
def PART(x,xnew):
    rows = x.shape[0]
    cols  = x.shape[1]
    YCAL=FOBJ(x)
    NEW=FOBJ(xnew) #xnew vem da rotina velocidade!!!!
    for i in range(rows):
        if(YCAL[i]>NEW[i]):
            x[i,]=np.copy(xnew[i,])
    PBEST=np.copy(x)        
    return PBEST

In [0]:
def PSO(W,C1,C2,NPAR,ITE,PAR,MAX,MIN):
    #rows = x.shape[0]
    #cols  = x.shape[1]
    x=Enxame(PAR,NPAR,MAX,MIN)# gera populacao inicial aleatoria
    PBEST=np.copy(x) # inicialmente eh aleatorio
    YCAL=FOBJ(x) # estima a funcao nos valores aleatorios
    best=np.argmin(YCAL)
    GBEST=PBEST[best] # melhor global: isto primeira interacao
    BEST=YCAL[best]
    VEL=Enxame(PAR,NPAR,MAX,MIN) # velocidades define aleatoria no primeiro uso
    
    for i in range(ITE):
        xnew,VEL=VE(VEL,x,GBEST,PBEST,W,C1,C2,MAX,MIN)# nova atualizacao de x utilizando as velocidades
        PBEST=PART(x,xnew) #atualizcao de PBEST (sempre atualiza com a nova busca)
        #YCAL=FOBJ(xnew)
        YCAL=FOBJ(PBEST)
        new=np.argmin(YCAL)
        NEW=YCAL[new]
        if(NEW<BEST):
            GBEST=xnew[new]
            BEST=NEW
        x=xnew
        Y=FOBJ(xnew)
        M=np.hstack((x, np.atleast_2d(Y).T))
    return x,M,BEST
        

In [0]:
'''  
Programa principal a rigor os valores de W,C1,C2 nao precisavam estar aqui mas esta por conta de implemntacao
com objetivo distinto desta q usa o mesmo codigo como codigo inicial
'''
W=0.75
C1=2
C2=2
NPAR=20 #PARTICULAS
ITE=500 #ITERACOES
PAR=2 #NUM DE PARAMETROS A SER OTIMIZADOS
MAX=[1,1] # MAXIMO DE CADA PARAMETRO
MIN=[-1,-1] # MINIMO DE CADA PARAMETRO
x,M,BEST=PSO(W,C1,C2,NPAR,ITE,PAR,MAX,MIN)
print('melhor',BEST)
print(M)
Y_ordenado = sorted(M,key=lambda M: M[2])
print(Y_ordenado)


melhor 0.00010704021183360856
[[ 4.00000000e-01  7.27222533e-01  3.25341401e+01]
 [ 5.97176409e-01  4.00000000e-01  3.50452200e-01]
 [ 4.00000000e-01  1.11660524e+00  9.18693588e+01]
 [ 9.83445025e-01  4.00000000e-01  3.21677876e+01]
 [ 8.77339136e-01 -3.37936890e-01  1.22706302e+02]
 [ 3.49814816e-01  4.45616636e-01  1.08715533e+01]
 [ 8.27876831e-01  6.55722223e-01  1.17585043e-01]
 [ 3.20243206e-01  4.69042880e-01  1.38933538e+01]
 [ 3.64054356e-01  2.74167496e-01  2.41038701e+00]
 [ 4.00000000e-01  4.00000000e-01  6.12000000e+00]
 [ 4.00868089e-01  6.72511898e-01  2.65545897e+01]
 [ 4.67277984e-01  4.47259692e-01  5.52381634e+00]
 [ 8.51608618e-01  1.14577441e+00  1.77071711e+01]
 [ 4.00000000e-01  4.00000000e-01  6.12000000e+00]
 [ 4.00000000e-01  9.52199823e-02  7.79645069e-01]
 [ 1.16511142e+00  9.88389784e-01  1.36503613e+01]
 [ 4.00000000e-01  6.71084444e-01  2.64807309e+01]
 [ 1.00730555e+00  4.00000000e-01  3.77812944e+01]
 [ 3.64827949e-01  9.85905116e-01  7.31311969e+01]
 